<a href="https://colab.research.google.com/github/aksharved/Used_Motorcycle_Price_Prediction/blob/main/MotorcyclePricesModel.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split, RandomizedSearchCV, KFold
from sklearn.base import clone
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer

from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor

from sklearn.cluster import KMeans
from sklearn.decomposition import PCA

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score, silhouette_score

import warnings
warnings.filterwarnings("ignore")

pd.set_option("display.max_columns", None)
sns.set_theme(style="whitegrid")

In [12]:
from google.colab import files

uploaded = files.upload()

Saving BIKE DETAILS.csv to BIKE DETAILS (1).csv

In [13]:
df = pd.read_csv("BIKE DETAILS.csv")

print("Dataset shape:", df.shape)
display(df.head())

Dataset shape: (1061, 7)

,name,selling_price,year,seller_type,owner,km_driven,ex_showroom_price
0,Royal Enfield Classic 350,175000,2019,Individual,1st owner,350,NaN
1,Honda Dio,45000,2017,Individual,1st owner,5650,NaN
2,Royal Enfield Classic Gunmetal Grey,150000,2018,Individual,1st owner,12000,148114.0
3,Yamaha Fazer FI V 2.0 [2016-2018],65000,2015,Individual,1st owner,23000,89643.0
4,Yamaha SZ [2013-2014],20000,2011,Individual,2nd owner,21000,NaN

In [14]:
print("columns:")
print(df.columns)

print("general dataset information:")
df.info()

print("Missing values: " )
print(df.isnull().sum())

print("Summary statistics: ")
display(df.describe())

columns:
Index(['name', 'selling_price', 'year', 'seller_type', 'owner', 'km_driven',
       'ex_showroom_price'],
      dtype='object')
general dataset information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1061 entries, 0 to 1060
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   name               1061 non-null   object
 1   selling_price      1061 non-null   int64
 2   year               1061 non-null   int64
 3   seller_type        1061 non-null   object
 4   owner              1061 non-null   object
 5   km_driven          1061 non-null   int64
 6   ex_showroom_price  626 non-null    float64
dtypes: float64(1), int64(3), object(3)
memory usage: 58.2+ KB
Missing values:
name                   0
selling_price          0
year                   0
seller_type            0
owner                  0
km_driven              0
ex_showroom_price    435
dtype: int64
Summary statistics:

       selling_price         year      km_driven  ex_showroom_price
count    1061.000000  1061.000000    1061.000000       6.260000e+02
mean    59638.151744  2013.867107   34359.833176       8.795871e+04
std     56304.291973     4.301191   51623.152702       7.749659e+04
min      5000.000000  1988.000000     350.000000       3.049000e+04
25%     28000.000000  2011.000000   13500.000000       5.485200e+04
50%     45000.000000  2015.000000   25000.000000       7.275250e+04
75%     70000.000000  2017.000000   43000.000000       8.703150e+04
max    760000.000000  2020.000000  880000.000000       1.278000e+06

In [15]:
print("seller type counts:")
print(df["seller_type"].value_counts())

print("owner counts:")
print(df["owner"].value_counts())

print("number of unique motorcycle names:", df["name"].nunique())

print("top 20 motorcycle names:")
print(df["name"].value_counts().head(20))

seller type counts:
seller_type
Individual    1055
Dealer           6
Name: count, dtype: int64
owner counts:
owner
1st owner    924
2nd owner    123
3rd owner     11
4th owner      3
Name: count, dtype: int64
number of unique motorcycle names: 279
top 20 motorcycle names:
name
Bajaj Pulsar 150                 41
Royal Enfield Classic 350        27
Honda Activa [2000-2015]         23
Honda CB Hornet 160R             22
Bajaj Pulsar 180                 20
Royal Enfield Thunderbird 350    19
Hero Honda Splendor Plus         17
Yamaha FZ S V 2.0                16
Bajaj Discover 125               16
Honda Shine                      15
Honda Activa 3G                  15
Honda CB Unicorn 150             14
TVS Apache RTR 160               14
Bajaj Pulsar 135 LS              13
Yamaha FZ16                      12
Honda Activa 5G                  12
Bajaj Discover 100               11
Hero Honda CBZ extreme           11
Bajaj Pulsar 150 [2001-2011]     11
Hero Glamour 125                 11
Name: count, dtype: int64